config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  get '/manual', to: 'home#manual'
  get '/dashboard', to: 'dashboard#index'
  get '/admin', to: 'admin#index'
  get '/settings/edit', to: 'settings#edit'
  put '/settings', to: 'settings#update'
  post '/synchronize', to: 'dashboard#synchronize'
  get '/premium', to: 'premium#index'
  delete '/alt_character', to: 'dashboard#remove_alt'

  devise_scope :user do
     get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthenticatedController
  before_action :check_manual, only: [:index]

  def index
    # Fetch information on a character the first time the dashboard is visited
    EveSwaggerInterfaceService.new(current_user).char_information unless current_user.corp_id
  end

  def synchronize
    alt_character = current_user.alt_characters.find_by_id(params[:alt_character_id])
    if alt_character
      sync_contacts = SynchronizeContacts.perform(user: current_user, alt: alt_character, source: :manual)
      if sync_contacts.success?
        flash[:notice] = "Sync of contacts to #{alt_character.name} successful"
      else
        sync_contacts.errors.messages[:sync].each do |message|
          flash[:alert] = message
        end
      end
    end
    redirect_to dashboard_path
  end

  def remove_alt
    alt_character = current_user.alt_characters.find(params[:alt_character_id])
    alt_character.delete
    redirect_to dashboard_path
  end

  def check_manual
    unless current_user.viewed_manual
      flash[:notice] = "Welcome to Alt Contact Sync, to view instructions on how to use, check out our <a href='#{manual_path}'>Manual</a>".html_safe
      flash[:html_safe] = true
    end
  end

end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="text-center bordered-container">
      <h3>
        <%= current_user.name %>
        <% if current_user.corp_name %>
          <br><small><small><%= current_user.corp_name %></small></small>
        <% end %>
        <% if current_user.ally_name %>
          <br><small><small><%= current_user.ally_name %></small></small>
        <% end %>
      </h3>
      <%= image_tag "https://imageserver.eveonline.com/Character/#{current_user.character_id}_128.jpg", class: 'avatar-img' %><br>
      <span>
        Premium: <%= current_user.premium? ? "#{(current_user.premium_expires_at - Time.now).to_i/86400} days left" : 'inactive'%> <small>(<%= link_to (current_user.premium? ? "Add" : "Activate"), premium_path, class: 'premium' %>)</small>
      </span>
    </div>

    <div class="text-center bordered-container">
      <h4>Settings</h4>
      <table>
        <tr>
          <td class="text-left">Sync Character Contacts</td>
          <td><%= current_user.settings.sync_char_contacts ? '&#10003;'.html_safe : '&#10007;'.html_safe %></td>
        </tr>
        <tr>
          <td class="text-left">Sync Corp Contacts</td>
          <td><%= current_user.settings.sync_corp_contacts ? '&#10003;'.html_safe : '&#10007;'.html_safe %></td>
        </tr>
        <tr>
          <td class="text-left">Sync Alliance Contacts</td>
          <td><%= current_user.settings.sync_ally_contacts ? '&#10003;'.html_safe : '&#10007;'.html_safe %></td>
        </tr>
        <% if current_user.premium? %>
        <tr>
          <td class="text-left">Auto Sync Contacts</td>
          <td><%= current_user.settings.auto_sync_contacts ? '&#10003;'.html_safe : '&#10007;'.html_safe %></td>
        </tr>
        <% end %>
      </table>
      <span class="text-center">
        <%= button_to "Edit Settings", settings_edit_path, class: 'btn btn-primary', method: :get %>
      </span>
    </div>
  </div>
  <div class="col-md-8">
    <ul class="unstyled">
      <li class="bordered-container row row-flex">
        <div class="col-md-7">
          <div class="row row-flex">
            <div class="col-xl-5 col-md-6">
              <%= image_tag "https://image.eveonline.com/Character/0_128.jpg", class: 'avatar-img' %>
            </div>
            <div class="col-xl-7  col-md-6">
              <span>Add a Character</span>
            </div>
          </div>

        </div>
        <div class="col-md-5 text-right">
          <span>
            <%= link_to image_tag("https://web.ccpgamescdn.com/eveonlineassets/developers/eve-sso-login-black-small.png"), user_crest_omniauth_authorize_path %>
          </span>
        </div>
      </li>
      <% current_user.alt_characters.each do |alt_character| %>
        <li class="bordered-container row row-flex">
          <div class="col-md-7">
            <div class="row row-flex">
              <div class="col-xl-5 col-md-6">
                  <%= image_tag "https://image.eveonline.com/Character/#{alt_character.character_id}_128.jpg", class: 'avatar-img' %>
              </div>
              <div class="col-xl-7  col-md-6">
                <%= alt_character.name %><br>
                <% if current_user.premium? %>
                <small>Label: <%= alt_character.label_name %></small><br>
                <% end %>
                <small><%= "Last Sync: #{alt_character.time_since_last_sync}" %></small>
              </div>
            </div>
          </div>
          <div class="col-md-5 text-right">
            <%= button_to "Sync", synchronize_path(params: {alt_character_id: alt_character.id}), method: :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %>
            <%= button_to "Remove", alt_character_path(params: {alt_character_id: alt_character.id}), method: :delete, class: 'btn btn-warning', form: {style: 'display:inline-block;'} %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>