config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  get '/manual', to: 'home#manual'
  get '/dashboard', to: 'dashboard#index'
  get '/admin', to: 'admin#index'
  get '/settings/edit', to: 'settings#edit'
  put '/settings', to: 'settings#update'
  post '/synchronize', to: 'dashboard#synchronize'
  get '/premium', to: 'premium#index'
  delete '/alt_character', to: 'dashboard#remove_alt'

  devise_scope :user do
     get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/models/settings.rb
class Settings < ApplicationRecord
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < AuthenticatedController

  def edit
  end

  def update
    current_user.settings.update(settings_params)

    current_user.alt_characters.each do |alt|
      label = params["label_#{alt.id}"].to_i
      if label == AltCharacter::DEFAULT_LABEL["label_id"]
        alt.update(label_id: label, label_name: AltCharacter::DEFAULT_LABEL["label_name"])
      elsif label != alt.label_id
        label_hash = alt.labels.detect {|l| l["label_id"] == label }
        alt.update(label_id: label, label_name: label_hash["label_name"])
      end
    end

    redirect_to dashboard_path
  end

  private

  def settings_params
    params.permit(:sync_char_contacts, :sync_corp_contacts, :sync_ally_contacts, :auto_sync_contacts)
  end

end

app/views/settings/edit.html.erb
<h3>Settings</h3>
<div class="row">
  <div class="col-sm-12">
    <%= form_tag(settings_path, method: :put, class: 'bordered-container') do %>
      <h5>Sync Options</h5>
      <%= hidden_field_tag :sync_char_contacts, "0" %>
      <%= label_tag :sync_char_contacts do %>
        <%= check_box_tag :sync_char_contacts, "1", current_user.settings.sync_char_contacts %>
        Sync Character Contacts
      <% end %></br>

      <%= hidden_field_tag :sync_corp_contacts, "0" %>
      <%= label_tag :sync_corp_contacts do %>
        <%= check_box_tag :sync_corp_contacts, "1", current_user.settings.sync_corp_contacts %>
        Sync Corporation Contacts
      <% end %></br>

      <%= hidden_field_tag :sync_ally_contacts, "0" %>
      <%= label_tag :sync_ally_contacts do %>
        <%= check_box_tag :sync_ally_contacts, "1", current_user.settings.sync_ally_contacts %>
        Sync Alliance Contacts
      <% end %></br>

      <% if current_user.premium? %>

        <%= hidden_field_tag :auto_sync_contacts, "0" %>
        <%= label_tag :auto_sync_contacts do %>
          <%= check_box_tag :auto_sync_contacts, "1", current_user.settings.auto_sync_contacts %>
          Automatically Sync Contacts
        <% end %></br>

        <% if current_user.alt_characters.present? %>
          <h5>Assign contacts to labels</h5>
          <table class="left">
          <% current_user.alt_characters.each do |alt| %>
            <tr>
              <td><%= label_tag alt.name%></td>
              <td><%= select_tag "label_#{alt.id}", options_for_select(alt.labels.collect {|i|[i["label_name"], i["label_id"]]}, [alt.label_name, alt.label_id]) %></td>
            </tr>
          <% end %>
          </table>
        <% end %>
      <% end %>

      <%= submit_tag "Update", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>