config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "home#index"
  get '/manual', to: 'home#manual'
  get '/dashboard', to: 'dashboard#index'
  get '/admin', to: 'admin#index'
  get '/settings/edit', to: 'settings#edit'
  put '/settings', to: 'settings#update'
  post '/synchronize', to: 'dashboard#synchronize'
  get '/premium', to: 'premium#index'
  delete '/alt_character', to: 'dashboard#remove_alt'

  devise_scope :user do
     get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/views/layouts/partials/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/partials/_nav_bar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to 'Alt Contact Sync', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Manual', manual_path, class: "nav-link #{current_page?(:controller => 'home', :action => 'manual') ? 'active' : ''}" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Dashboard', dashboard_path, class: "nav-link #{current_page?(:controller => 'dashboard', :action => 'index') ? 'active' : ''}" %>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Admin', admin_path, class: "nav-link #{current_page?(:controller => 'admin', :action => 'index') ? 'active' : ''}" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Premium', premium_path, class: "nav-link #{current_page?(:controller => 'premium', :action => 'index') ? 'active' : ''}" %>
        </li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <ul class="navbar-nav mt-auto">
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :get, class: 'nav-link' %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mt-auto">
        <li class="nav-item">
          <%= link_to image_tag("https://web.ccpgamescdn.com/eveonlineassets/developers/eve-sso-login-black-large.png"), user_crest_omniauth_authorize_path %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>